### ISSUE TITLE
Opaque error with `msgpack` after incorporating `dbt-aql` into project

### ISSUE THREAD

**Issue by zkeller89** [bcodell/dbt-activity-schema#39]
Hey @bcodell - this is what I was referencing earlier today in the LinkedIn dm. 

This error began occurring after running `dbt deps` with the package referenced locally.

Notes on environment:
* I'm using `pipenv` for some semblance of environment management. 
* BigQuery is the data warehouse.

dbt version:
```
(ws-activity-schema) ➜  ws-activity-schema dbt --version
Core:
  - installed: 1.7.3
  - latest:    1.7.3 - Up to date!

Plugins:
  - bigquery: 1.7.2 - Up to date!
```

python version:
```
(ws-activity-schema) ➜  ws-activity-schema python --version 
Python 3.11.6
```

command run to product error:
`dbt compile -s question_answered`

stack trace:
```
============================== 21:06:08.039653 | 1e521574-f151-43d9-a8a0-294476b57c66 ==============================
[0m21:06:08.039653 [info ] [MainThread]: Running with dbt=1.7.3
[0m21:06:08.040253 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': '/Users/zacharykeller/workstep_gh/ws-activity-schema/logs', 'profiles_dir': '/Users/zacharykeller/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt compile -s question_answered', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:06:08.432956 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '1e521574-f151-43d9-a8a0-294476b57c66', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113ad2cd0>]}
[0m21:06:08.487266 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '1e521574-f151-43d9-a8a0-294476b57c66', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11447ee50>]}
[0m21:06:08.488351 [info ] [MainThread]: Registered adapter: bigquery=1.7.2
[0m21:06:08.519927 [debug] [MainThread]: checksum: c95636796e12235e48c0560a0bb6a50e98827ef72e7ea1fe07a97c38c91661e1, vars: {}, profile: , target: , version: 1.7.3
[0m21:06:08.535198 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m21:06:08.535742 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '1e521574-f151-43d9-a8a0-294476b57c66', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114734890>]}
[0m21:06:09.965769 [error] [MainThread]: Encountered an error:
can not serialize 'Undefined' object
[0m21:06:09.969761 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 168, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 197, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 244, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/cli/requires.py", line 271, in wrapper
    manifest = ManifestLoader.get_full_manifest(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/parser/manifest.py", line 318, in get_full_manifest
    manifest = loader.load()
               ^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/parser/manifest.py", line 567, in load
    self.write_manifest_for_partial_parse()
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/parser/manifest.py", line 753, in write_manifest_for_partial_parse
    manifest_msgpack = self.manifest.to_msgpack(extended_mashumaro_encoder)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 71, in __mashumaro_to_msgpack__
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/dbt/parser/manifest.py", line 138, in extended_mashumaro_encoder
    return msgpack.packb(data, default=extended_msgpack_encoder, use_bin_type=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zacharykeller/.local/share/virtualenvs/ws-activity-schema-_kVNeSdF/lib/python3.11/site-packages/msgpack/__init__.py", line 36, in packb
    return Packer(**kwargs).pack(o)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  [Previous line repeated 2 more times]
  File "msgpack/_packer.pyx", line 291, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Undefined' object

[0m21:06:09.972200 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_wall_clock_time": 2.0043304, "process_user_time": 2.983274, "process_kernel_time": 0.297102, "process_mem_max_rss": "146317312", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m21:06:09.972712 [debug] [MainThread]: Command `dbt compile` failed at 21:06:09.972598 after 2.00 seconds
[0m21:06:09.973069 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d4b1790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113aa6fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113aa4c90>]}
[0m21:06:09.973396 [debug] [MainThread]: Flushing usage events

```

Happy to provide any additional info, appreciate any help!

**Comment by bcodell** [comment]
Hey @zkeller89 - thanks for opening this! I've been able to run the package on dbt 1.7 on Bigquery, so I don't think this is a dependency issue. I tried searching for `TypeError: can not serialize 'Undefined' object` in dbt Slack and found a few different posts, all of which seemed to point to formatting issues in model config blocks. Could you share the config you've defined for your `question_answered` model? Feel free to publish pseudo-code if that's easier/more secure.

**Comment by bcodell** [comment]
Played around with this a bit more and was able to reproduce. In the example config block below, when defining the `data_types` parameter, the key I defined for the feature name is not in quotes, so Jinja thinks `referrer_url` is a variable that isn't defined, thus throwing the `'Undefined' object` error. There's probably more than one way to mis-enter the syntax, though, so feel free to share the config block in your model and I can help debug if still needed.

```
{{ config(
    data_types={
        referrer_url: dbt.type_string(), -- should be 'referrer_url' in quotes
    },
    stream='customer_stream'
)}}
```

**Comment by zkeller89** [comment]
Ok wow this was completely user error. While it wasn't specifically how you recreated it, your pointing me towards the config block was super useful.

...I was using `type_text()` instead of `type_string()` ... :|

my only excuse is that i've been doing too much yaml in google workflows recently

really appreciate your help, undoubtedly will nudge over here again if i run into anything else. Thank you!

**Comment by bcodell** [comment]
Haha happens to everyone! And dbt is certainly not the friendliest when it comes to error messages for debugging. I've spent a fair bit of time adding error handling to circumvent the typically nondescript stack traces that dbt macro-related errors will throw, particularly in building activities and writing aql. Excited to hear your feedback!

**Comment by redthor** [comment]
this issue report helped me.

I had a tiny typo `'country': type_stringt(),`  ... dbt does not make it easy to track down 💦
